// Generated by CoffeeScript 1.7.1
(function() {
  var escapeshell, fs, process;

  fs = require('fs');

  process = require('child_process');

  escapeshell = function(cmd) {
    return '"' + cmd.replace(/(["\s'$`\\])/g, '\\$1') + '"';
  };

  module.exports = function(input, output, callback) {
    var err, inputStr, pdfunite;
    inputStr = '';
    if ((input == null) || (output == null) || (callback == null) || input.length === 0 || output.length === 0) {
      err = new Error('Missing parameter');
      callback(err);
      return false;
    }
    if (!Array.isArray(input)) {
      err = new Error('Parameter `input` must be an Array');
      callback(err);
      return false;
    }
    input.forEach(function(item) {
      return inputStr += escapeshell(item) + ' ';
    });
    pdfunite = process.exec("pdfunite " + inputStr + " " + output, function(err, stdout, stderr) {
      if (err != null) {
        callback(err);
        return false;
      }
    });
    return pdfunite.on('exit', function(code) {
      if (code === 0) {
        callback(null);
        return true;
      }
    });
  };

}).call(this);
